apiversion: v1
kind: Pod
metadata:
  name: wmts
  labels:
    app: wmts
spec:
  containers:
    - name: wmts-app
      env:
      - name: WMSSERVER
        value: http://otd-omar-single.rbtcloud.dev
      - name: WFSPORT
        value: 80
      - name: WFSSERVER
        value: http://otd-omar-single.rbtcloud.dev
      - name: WFSPORT
        value: 80
      - name: DBUSER
        value: wmts
      - name: DBPORT
        value: 5432
      - name: DBNAME
        value: omar_prod
      - name: DBUSER
        value: wmts
      - name: DBPASS
        value: abc123
      image: radiantbluetechnologies/wmts
      ports:
        - containerPort: 8080
   - name: wmtsdb
     env:
     - name:  POSTGRES_PASSWORD
       value: abc123
     - name: POSTGRES_USER
       value: wmts
     - name: POSTGRES_DB
       value: omar_prod
     image: postgres:latest 
     ports:
       - containerPort: 5432
         
